# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('article_text', models.TextField(blank=True, verbose_name='无字数限制')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='文本内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='生成日期')),
                ('vote', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('publish', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.TextField(blank=True)),
                ('chairman', models.CharField(default='', max_length=5)),
                ('source', models.URLField(default='')),
                ('pub_date', models.DateField(verbose_name='生效时间')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='BranchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='文本内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='生成日期')),
                ('thumb_up', models.IntegerField(default=0, verbose_name='支持数')),
                ('thumb_down', models.IntegerField(default=0, verbose_name='反对数')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['thumb_down'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='发送日期')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=16)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('avatar', models.ImageField(blank=True, upload_to='myapp/static/myapp/storage/')),
                ('score', models.IntegerField(default=0)),
                ('brief_intro', models.CharField(blank=True, max_length=40)),
                ('long_intro', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('fans', models.ManyToManyField(blank=True, to='myapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
                ('topic_text', models.CharField(max_length=200)),
                ('topic_icon', models.ImageField(upload_to='myapp/static/myapp/storage/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='myapp.Topic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='myapp.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='addresser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresser', to='myapp.Profile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='topics',
            field=models.ManyToManyField(blank=True, to='myapp.Topic'),
        ),
        migrations.AddField(
            model_name='article',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Branch'),
        ),
    ]
